version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: church_management_system_db
      MYSQL_USER: alvin
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/church_management_system_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123

      MAIL_USERNAME: athanasalvin@gmail.com
      MAIL_PASSWORD: rgbs amid hupv esra
      MAIL_FROM: athanasalvinl@gmail.com

volumes:
  mysql_data:
